apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: awe9omzz1-java-springboot
  janus-idp.io/tekton: awe9omzz1-java-springboot
  backstage.io/kubernetes-id: awe9omzz1-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: awe9omzz1-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
